### ISSUE TITLE
Manual run from composed service

### ISSUE THREAD

**Issue by Glideh** [Salvoxia/immich-folder-album-creator#14]
If my service is configured on the compose stack to run CRONly like:

```yml
  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://immich_server:3001/api
      API_KEY: YQTOPW6MEY4SLPC37LyXrbtuXoULt6Hl1F9DYoePXw
      ROOT_PATH: /volume1/Photos
      CRON_EXPRESSION: "0 0 * * *"
      TZ: Europe/Paris
```

Is there a way to run the job manually ?
