### ISSUE TITLE
`.albumprops` File: `archive` property is not respected

### ISSUE THREAD

**Issue by benji1512** [Salvoxia/immich-folder-album-creator#150]
Hello, first off, thanks for making this!

I'm running into an issue where the album creator is not respecting the `archive` property within the `.albumprops` file. In other words, It's not archiving photos in folders that have an `.albumprops` file with `archive: true` set.

All the other `.albumprops` properties are being applied correctly and the debug output shows it reading the file and recognizing that archive has been set to `true`.
```
 level=DEBUG msg=Albumprops: dogs_photos -> {'override_name': 'Dog Pictures', 'description': 'All the dogs.', 'share_with': [], 'thumbnail_setting': 'first', 'sort_order': 'desc', 'archive': True, 'comments_and_likes_enabled': False}
```

This is consistent at least as far back as v0.18.2 (with Immich v1.125.2), though that's as far as I tested.

Miscellaneous info below.
Thanks!

---

**Other Potentially Relevant(?) Info:**
My `.albumprops` file:
```yaml
# Album Name overriding the album name generated from folder names
override_name: "Dog Pictures"
description: "All the dogs."
# Set album thumbnail, valid values: first, last, random or fully qualified path of an asset that is (or will be) assigned to the album
thumbnail_setting: "first"
# Sort order in album, valid values: asc, desc
sort_order: "desc"
# Flag indicating whether to archive images added to this album, valid values: true, false
archive: true
# Flag indicating whether assets in this albums can be commented on and liked
comments_and_likes_enabled: false
```

Docker Compose Entry
```yaml
  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    volumes:
      - /home/benji/Pictures:/Pictures
    restart: unless-stopped
    environment:
      API_URL: http://immich_server:2283/api
      API_KEY: <key>
      ROOT_PATH: /Pictures
      # Run every night at 2:30am
      CRON_EXPRESSION: "30 2 * * *"
      # Do not delete empty albums or remove offline assets
      SYNC_MODE: "0"
      ALBUM_LEVELS: "1"
      UNATTENDED: "1"
      # Album Props Stuff
      READ_ALBUM_PROPERTIES: "true"
      UPDATE_ALBUM_PROPS_MODE: "1"
      FIND_ASSETS_IN_ALBUMS: "true"
      FIND_ARCHIVED_ASSETS: "true"
      LOG_LEVEL: "DEBUG"
```
