### ISSUE TITLE
[BUG] ALBUM_LEVELS=3,3 also creates albums for level 2

### ISSUE THREAD

**Issue by ltctceplrm** [Salvoxia/immich-folder-album-creator#152]
Hello, I'm not sure if this is intended or if it's a bug but if I set the ALBUM_LEVELS=3,3 then it also adds an album for sub level 2 if there is no sub level 3.
This is my docker compose:
```yaml
services:
  immich-folder-album-creator:
    environment:
      - API_URL=URL
      - API_KEY=API
      - ROOT_PATH=/ROOT_PATH/
      - ALBUM_LEVELS=3,3
      - SYNC_MODE=1
      - RUN_IMMEDIATELY=true
      - MODE=CREATE
      - UNATTENDED=1
      - DELETE_CONFIRM=1
      - FIND_ASSETS_IN_ALBUMS=1
    image: salvoxia/immich-folder-album-creator:latest
    command: /script/immich_auto_album.sh
networks: {}
```
And this is an example of my folder structure:
```
/photos/
  └──  2025
      └── 04
          └── Birthday
                    └── Phone
                    └── Canon
      └── 03
      └── 02
      └── 01
          └── New Year
  └──  2024
      └── 12
          └── New Year's Eve
      └── 11
          └── Birthday
        └── Trip
    └── 10
    └── 09
```

Currently it creates albums for 01,02,... but I'd like to ignore those and only have folders that have 3 levels be made into albums.
