### ISSUE TITLE
Need assistance with creating nested folder albums in docker compose

### ISSUE THREAD

**Issue by Gitama-Senjou** [Salvoxia/immich-folder-album-creator#159]
Okay, so I'm perfectly fine creating an album for each folder. Problem is that one folder has 5 folders inside. Two of those have again folders inside them.

How do I replicate this in Docker Compose?

**Comment by Salvoxia** [comment]
> Okay, so I'm perfectly fine creating an album for each folder. 

I assume this is targeted at the fact that Immich does not support nested albums?

Now, depending on how exactly you would like your albums to be named you have a couple of options. Assume the following folder structure:
```
/external_libs/photos/
├── 2020/
│   ├── 02 Feb/
│   │   └── Vacation/
│   ├── 08 Aug/
│   │   └── Vacation/
├── Birthdays/
│   ├── John/
│   └── Jane/
└── Skiing 2023/
```

If I take what you said literally (one album per folder), you could configure the container like this: 
```
---
services:
  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://immich_server:2283/api
      API_KEY: <key>
      ROOT_PATH: /external_libs/photos
      ALBUM_LEVELS: -1
      ALBUM_SEPARATOR: ""
      CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Berlin
```
By setting `ALBUM_LEVELS: -1`, the script will take the create one album per folder it finds an asset in. The example above would then result in the following albums (assuming there is an asset an each of these folders):
  - `2020`
  - `02 Feb`
  - `Vacation` (containing assets from `/external_libs/photos/2020/02 Feb/Vacation` as well as  `/external_libs/photos/2020/08 Aug/Vacation`
  - `Birthdays`
  - `John`
  - `Jane`
  - `Skiing 2023`

So that setting will not preserve the context to a folder's parent folder(s). If you would like that, may go this route:
```
---
services:
  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://immich_server:2283/api
      API_KEY: <key>
      ROOT_PATH: /external_libs/photos
      ALBUM_LEVELS: 3
      ALBUM_SEPARATOR: " - "
      CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Berlin
```
By setting `ALBUM_LEVELS: 3` and `ALBUM_SEPARATOR: " - "` the script will construct album names from the top three folders for each asset below  `ROOT_PATH` and separate each folder name with ` - `. This would result in the following albums (again assuming there is an asset in each of these folders):
  - `2020`
  - `2020 - 02 Feb`
  - `2020 - 02 Feb - Vacation`
  - `2020 - 08 Aug - Vacation`
  - `Birthdays`
  - `Birthdays - John`
  - `Birthdays - Jane`
  - `Skiing 2023`

If you could share how you would like your albums to be named, I can show up more options.
