### ISSUE TITLE
docker compose with multiple root paths?

### ISSUE THREAD

**Issue by ballerbude** [Salvoxia/immich-folder-album-creator#169]
Using multiple root paths when executing the docker image manually is done by attaching -r argument as many times as necessary, according to the documentation.

But I haven't found anything on declaring multiple root paths using the docker-compose.yml.

How would the correct entry look like? Something like this?

```
  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    volumes:
     - /path/to/secret/file:/immich_api_key.secret:ro
     # mount needed for .albumprops to work
     - /path/to/my/photos:/external_libs/photos
    environment:
      API_URL: http://immich_server:2283/api
      API_KEY_FILE: /immich_api_key.secret
      ROOT_PATH: /mnt/photos1,/mnt/photos2
      CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Berlin
```
