### ISSUE TITLE
Share created albums with partner

### ISSUE THREAD

**Issue by janwdev** [Salvoxia/immich-folder-album-creator#34]
Hey, thanks for the great script, it really helped me migrate to immich! I have a little feature request:
I have partner sharing turned on for the immich family account so all the family members can see all of the family images.
Would it be possible to implement a solution, that allows to share all through this script newly created albums with the partner accounts, so they show up in the shared section of their accounts?

The great amount of all family albums would make this feature very handy!
Thanks in advance already for your answer!

**Comment by Salvoxia** [comment]
Hi,

that's certainly possible.
You would have to pass the list of users to share the created albums with as an argument / environment variable `--share-with User1:User2:User3` /  `-e SHARE_WITH="User1:User2:User3"`.
Sharing would only happen when an album is initially created, not when new assets are added to an existing album.

Would that work for you?

Best Regards,
Salvoxia

**Comment by janwdev** [comment]
This would work wonderful, however im not able to make it work yet, is this already implemented?
I use the script with docker compose and this is my compose file, maybe there is an error with it?

```
name: immich-albums
services:
  immich_albums-fam_create:
    container_name: immich_albums-fam_create
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://ip:port/api/
      API_KEY: myAPIKey
      ROOT_PATH: /mnt/media/family
      ALBUM_LEVELS: 2
      ALBUM_SEPARATOR: " - "
      SHARE_WITH: "user1@example.com:user2@example.com"
      CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Berlin
```
