### ISSUE TITLE
Error when implementing Docker Compose

### ISSUE THREAD

**Issue by Raffie1987** [Salvoxia/immich-folder-album-creator#70]
Dear,

I am trying to implement the plug in in the docker Compose. I added the following code:

immich-folder-album-creator:

container_name: immich_folder_album_creator

image: salvoxia/immich-folder-album-creator:latest

restart: unless-stopped

environment:
API_URL: https://photos.mydomain.nl/api/
API_KEY: mygeneratedapikey
ROOT_PATH: /usr/src/app/external
CRON_EXPRESSION: "30 * * * *"
TZ: Europe/Amsterdam

After I saved the Immich container won't start anymore. I am running OMV with DOcker Compose. When I try to start it says connection lost. When I remove this part, Immich starts again. I can reach the domain. Also with the Immich mobile app. What am I doing wrong?

**Comment by Salvoxia** [comment]
Hi,

since docker-compose is yaml, indentation is key. Could you please post your complete docker-compose.yml file for your Immich stack with and without the modifications formatted as code (Use three backticks ` ``` ` to start and to end a codeblock, so when posting your reply, it should look something like this:
```` 
  ```
  services:
     immich-server:
         ...
  ```
`````

Best Regards,
Salvoxia

**Comment by Raffie1987** [comment]
This is my Yaml flie:

YAML file

  ```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /srv/dev-disk-by-uuid-c14afaeb-571f-4c68-8c9d-d4acaf1e1848/Photos:/usr/src/app/external:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - immich.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
  ```
  In the .env file I added this code for NGINX Proxy Manager
  ```
PUBLIC_IMMICH_SERVER_URL=https://photos.roijackersnet.nl
    ```

without the plugin everything works fine. But after I added the previous post code Immich won't start anymore.

**Comment by Raffie1987** [comment]
The complete Yaml file is:

 ```
name: immich

services:
immich-server:
  container_name: immich_server
  image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
  # extends:
  #   file: hwaccel.transcoding.yml
  #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
  volumes:
    # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
    - /srv/dev-disk-by-uuid-c14afaeb-571f-4c68-8c9d-d4acaf1e1848/Photos:/usr/src/app/external:ro
    - /etc/localtime:/etc/localtime:ro
  env_file:
    - immich.env
  ports:
    - 2283:3001
  depends_on:
    - redis
    - database
  restart: always
  healthcheck:
    disable: false

immich-machine-learning:
  container_name: immich_machine_learning
  # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
  # Example tag: ${IMMICH_VERSION:-release}-cuda
  image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
  #   file: hwaccel.ml.yml
  #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
  volumes:
    - model-cache:/cache
  env_file:
    - immich.env
  restart: always
  healthcheck:
    disable: false

redis:
  container_name: immich_redis
  image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
  healthcheck:
    test: redis-cli ping || exit 1
  restart: always

database:
  container_name: immich_postgres
  image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
  environment:
    POSTGRES_PASSWORD: ${DB_PASSWORD}
    POSTGRES_USER: ${DB_USERNAME}
    POSTGRES_DB: ${DB_DATABASE_NAME}
    POSTGRES_INITDB_ARGS: '--data-checksums'
  volumes:
    # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
    - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
  healthcheck:
    test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
    interval: 5m
    start_interval: 30s
    start_period: 5m
  command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
  restart: always

volumes:
model-cache:

immich-folder-album-creator:

container_name: immich_folder_album_creator

image: salvoxia/immich-folder-album-creator:latest

restart: unless-stopped

environment:
API_URL: https://photos.mydomain.nl/api/
API_KEY: mygeneratedapikey
ROOT_PATH: /usr/src/app/external
CRON_EXPRESSION: "30 * * * *"
TZ: Europe/Amsterdam
 ```

When I start the docker compose container it gives the error "Connection Lost". Nothing more. When I remove the part for the plugin, it starts all the containers for Immich.

**Comment by Salvoxia** [comment]
Itendation does look odd. I fixed this, now looks like that. Can you try that by using the copy icon in the upper right corner of the code block?
```yaml
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /srv/dev-disk-by-uuid-c14afaeb-571f-4c68-8c9d-d4acaf1e1848/Photos:/usr/src/app/external:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - immich.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: https://photos.mydomain.nl/api/
      API_KEY: mygeneratedapikey
      ROOT_PATH: /usr/src/app/external
      CRON_EXPRESSION: "30 * * * *"
      TZ: Europe/Amsterdam

  volumes:
    model-cache:
```

**Comment by Raffie1987** [comment]
I have tried it with changed to my domain and added the api key. But it won't work. But now when I remove the plug-in, Immcih won't start either. If I put my previous code, everything works fine.

**Comment by Salvoxia** [comment]
That `connection lost`  thing must be something special to OMV, I am not familiar with it. Is there not any way to get to the plain Docker logs when trying to start a stack?

**Comment by Raffie1987** [comment]
When I started the code you sent me, it shows this error:

![ERROR](https://github.com/user-attachments/assets/79096c83-ee33-44ca-87df-02415d2db156)

**Comment by Salvoxia** [comment]
Hm, that's a bit better but not quite enough. I'll try to see if I can find something about getting Docker logs in OMV. Please bear with me.

**Comment by Salvoxia** [comment]
Ok, I spun up a VM, installed OMV, installed omv-extras, installed the Compose Plugin and tested the compose stack I posted. There is actually an error in it, and OMV presented me with this error message:
![image](https://github.com/user-attachments/assets/c1f146a1-c1a1-42d4-ae34-b5bb01d37c3b)
Yours does look similar, but it is cut off.
Please try the compose stack below, and if it fails again, please make sure to post the __COMPLETE__ error message.

__Important:__ Immich v1.118.0 released yesterday changes the port the webserver is running. So I updated the port Mapping the stack to the new port, but this only works with v1.118.0 or newer!

```yaml
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /srv/dev-disk-by-uuid-c14afaeb-571f-4c68-8c9d-d4acaf1e1848/Photos:/usr/src/app/external:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - immich.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: https://photos.mydomain.nl/api/
      API_KEY: mygeneratedapikey
      ROOT_PATH: /usr/src/app/external
      CRON_EXPRESSION: "30 * * * *"
      TZ: Europe/Amsterdam

volumes:
  model-cache:
```
