### ISSUE TITLE
Quotation marks in cron expression prevents schedule

### ISSUE THREAD

**Issue by DSchmidtDev** [Salvoxia/immich-folder-album-creator#93]
https://github.com/Salvoxia/immich-folder-album-creator/blob/32838d80ebe9d1060224b98fc6b3eee5b6b20e2a/docker/setup_cron.sh#L4

If cron expression contains quotation marks like e.g. doing 
```yaml
immich-folder-album-creator:
  image: salvoxia/immich-folder-album-creator:latest
  environment:
    - API_URL=""
    - CRON_EXPRESSION="0 1 * * *" # everyday at 01:00 AM
 ```
this leads to having the quotation marks in the crontab config as well and the task won't be scheduled.

Maybe adding some trimming to remove them or do I oversee something else?
