### ISSUE TITLE
Updating manually shared album causes share status to get reset

### ISSUE THREAD

**Issue by Toastie** [Salvoxia/immich-folder-album-creator#96]
Recently I noticed that every time after an album is updated due to new images being added to the external library the share status gets reset.

The album is shared manually (not automatically with the script) and if I understand the documentation correctly, then updating an album should not affect it's share state (See [Usage(docker)](https://github.com/Salvoxia/immich-folder-album-creator?tab=readme-ov-file#docker), under `SHARE_WITH`: "Sharing only happens if an album is actually created, not if new assets are added to it.").

Is there any way to change this? I'd like to keep the default behaviour of not automatically sharing albums but would like to preseve the status in case I manually share it with other users on the server. Ideally without having to use the per album/folder properties mechanism, as that would require me to additionally create such a configuration every time I want to share an album.

Section of my docker-compose file, if that prooves helpful
```  
immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://[REDACTED]:2283/api
      API_KEY: [REDACTED]
      ROOT_PATH: [REDACTED]
      CRON_EXPRESSION: "0 * * * *"
      ALBUM_LEVELS: "2,3"
      ALBUM_SEPARATOR: "/"
      SET_ALBUM_THUMBNAIL: random
      TZ: Europe/Berlin
```

Relevant section of the log:
```
time=2025-01-05T01:00:00.724+01:00 level=INFO msg=Detected Immich server version 1.123.0
time=2025-01-05T01:00:00.725+01:00 level=INFO msg=Requesting all assets
time=2025-01-05T01:00:00.806+01:00 level=INFO msg=9 photos found
time=2025-01-05T01:00:00.807+01:00 level=INFO msg=Sorting assets to corresponding albums using folder name
time=2025-01-05T01:00:00.807+01:00 level=INFO msg=1 albums identified
time=2025-01-05T01:00:00.807+01:00 level=INFO msg=Album list: ['ALBUM_NAME']
time=2025-01-05T01:00:00.807+01:00 level=INFO msg=Listing existing albums on immich
time=2025-01-05T01:00:01.049+01:00 level=INFO msg=34 existing albums identified
time=2025-01-05T01:00:01.084+01:00 level=INFO msg=Creating albums if needed
time=2025-01-05T01:00:01.084+01:00 level=INFO msg=Adding assets to album ALBUM_NAME
time=2025-01-05T01:00:01.178+01:00 level=INFO msg=1 new assets added to ALBUM_NAME
time=2025-01-05T01:00:01.251+01:00 level=INFO msg=Using asset SOME_IMAGE as thumbnail for album ALBUM_NAME
time=2025-01-05T01:00:01.425+01:00 level=INFO msg=0 albums created
time=2025-01-05T01:00:01.426+01:00 level=INFO msg=Done!
```
