### ISSUE TITLE
Error with API key File

### ISSUE THREAD

**Issue by fritzi001** [Salvoxia/immich-folder-album-creator#97]
Hello
i added the album creator to my immich compose File when it was Version 0.15
i used a secret File to pass the API Key to the Container. That worked.

Immich is still working fine but as i try run your script now with the new docker File, even with the old version with secrets i get an error
Tryrun with:
`docker exec immich_folder_album_creator /bin/sh -c "/script/immich_auto_album.sh"`

Error:
`immich_auto_album.py: error: unrecognized arguments: /immich_api_key.secret`

when i look inside the container i can find the immich_api_key.secret file
The API Key showing there is fine.

my Docker Compose:

```
 immich-folder-album-creator:
    container_name: immich-folder-album-creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://immich-server:2283/api
      API_KEY_FILE: /immich_api_key.secret
      ROOT_PATH: /mnt/media/Archiv --album-levels=-1 --album-separator " - "
      CRON_EXPRESSION: "1 * * * *"
      TZ: Europe/Berlin
      SYNC_MODE: "1"
    volumes:
     - ./immich_api_key.secret:/immich_api_key.secret:ro
    networks:
      - immich
```
Immich is on latest version v1.123.0
 Folder:
![image](https://github.com/user-attachments/assets/1de2e608-119f-488b-a71e-163de6df3435)

Any ideas what could be the resason?
Any help is appreciated 
Thanks

**Comment by Salvoxia** [comment]
Looking at your `docker-compose` file, this line strikes me a little bit odd
```yaml
ROOT_PATH: /mnt/media/Archiv --album-levels=-1 --album-separator " - "
```
The error you receive also indicates too many positional parameters.
Could you try again with these environment vars?
```yaml
immich-folder-album-creator:
    container_name: immich-folder-album-creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://immich-server:2283/api
      API_KEY_FILE: /immich_api_key.secret
      ROOT_PATH: /mnt/media/Archiv
      ALBUM_LEVELS: 1
      ALBUM_SEPARATOR: " - "
      CRON_EXPRESSION: "1 * * * *"
      TZ: Europe/Berlin
      SYNC_MODE: "1"
```
